# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_system_user_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 650)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget {\n"
"background-color:white;\n"
"}\n"
"#mainBody {\n"
"background-color:white;\n"
"border:1px solid rgb(222, 222, 222);\n"
"border-radius:2px;\n"
"}\n"
"QLineEdit {\n"
"padding:3px;\n"
"border:1px solid grey;\n"
"border-radius:2px;\n"
"}\n"
"QLineEdit:hover {\n"
"border-color:black;\n"
"}\n"
"#cancelBtn {\n"
"background-color:rgb(255, 78, 43);\n"
"color:white;\n"
"border:none;\n"
"padding:8px;\n"
"border-radius:3px;\n"
"}\n"
"#cancelBtn:hover {\n"
"background-color: rgb(202, 33, 0);\n"
"}\n"
"#submitBtn {\n"
"background-color:rgb(0, 149, 109);\n"
"color:white;\n"
"border:none;\n"
"padding:8px;\n"
"border-radius:3px;\n"
"}\n"
"#submitBtn:hover {\n"
"background-color:rgb(0, 121, 89);\n"
"}\n"
"QDateEdit {\n"
"padding:3px;\n"
"border:1px solid grey;\n"
"border-radius:2px;\n"
"}\n"
"QDateEdit:hover {\n"
"border-color:black;\n"
"}\n"
"QComboBox {\n"
"padding:3px;\n"
"border:1px solid grey;\n"
"border-radius:2px;\n"
"}\n"
"QComboBox:hover {\n"
"border-color:black;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.mainBody = QtWidgets.QFrame(self.centralwidget)
        self.mainBody.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainBody.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainBody.setObjectName("mainBody")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainBody)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.frame = QtWidgets.QFrame(self.mainBody)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.frame)
        self.name_Frame = QtWidgets.QFrame(self.mainBody)
        self.name_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.name_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.name_Frame.setObjectName("name_Frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.name_Frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.name_Frame)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.name = QtWidgets.QLineEdit(self.name_Frame)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.verticalLayout_3.addWidget(self.name)
        self.verticalLayout_2.addWidget(self.name_Frame)
        self.address_Frame = QtWidgets.QFrame(self.mainBody)
        self.address_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.address_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.address_Frame.setObjectName("address_Frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.address_Frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.address_Frame)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.email = QtWidgets.QLineEdit(self.address_Frame)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.email.setFont(font)
        self.email.setObjectName("email")
        self.verticalLayout_4.addWidget(self.email)
        self.verticalLayout_2.addWidget(self.address_Frame)
        self.email_Frame = QtWidgets.QFrame(self.mainBody)
        self.email_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.email_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.email_Frame.setObjectName("email_Frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.email_Frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.email_Frame)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.phone_no = QtWidgets.QLineEdit(self.email_Frame)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.phone_no.setFont(font)
        self.phone_no.setObjectName("phone_no")
        self.verticalLayout_5.addWidget(self.phone_no)
        self.verticalLayout_2.addWidget(self.email_Frame)
        self.phone_no_Frame = QtWidgets.QFrame(self.mainBody)
        self.phone_no_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.phone_no_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.phone_no_Frame.setObjectName("phone_no_Frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.phone_no_Frame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.phone_no_Frame)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.comboBox = QtWidgets.QComboBox(self.phone_no_Frame)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_6.addWidget(self.comboBox)
        self.verticalLayout_2.addWidget(self.phone_no_Frame)
        self.buttons_Frame = QtWidgets.QFrame(self.mainBody)
        self.buttons_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttons_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttons_Frame.setObjectName("buttons_Frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.buttons_Frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(50)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cancelBtn_frame = QtWidgets.QFrame(self.buttons_Frame)
        self.cancelBtn_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cancelBtn_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cancelBtn_frame.setObjectName("cancelBtn_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.cancelBtn_frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cancelBtn = QtWidgets.QPushButton(self.cancelBtn_frame)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.cancelBtn.setFont(font)
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout_3.addWidget(self.cancelBtn)
        self.horizontalLayout_2.addWidget(self.cancelBtn_frame)
        self.submitBtn_frame = QtWidgets.QFrame(self.buttons_Frame)
        self.submitBtn_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.submitBtn_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.submitBtn_frame.setObjectName("submitBtn_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.submitBtn_frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.submitBtn = QtWidgets.QPushButton(self.submitBtn_frame)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.submitBtn.setFont(font)
        self.submitBtn.setObjectName("submitBtn")
        self.horizontalLayout_4.addWidget(self.submitBtn)
        self.horizontalLayout_2.addWidget(self.submitBtn_frame)
        self.verticalLayout_2.addWidget(self.buttons_Frame)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_5.addWidget(self.mainBody)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Add Customers Form"))
        self.label.setText(_translate("MainWindow", "Add System User"))
        self.label_2.setText(_translate("MainWindow", "User Name:"))
        self.name.setPlaceholderText(_translate("MainWindow", "Enter User Name"))
        self.label_3.setText(_translate("MainWindow", "Email:"))
        self.email.setPlaceholderText(_translate("MainWindow", "Enter Email ID"))
        self.label_4.setText(_translate("MainWindow", "Password:"))
        self.phone_no.setPlaceholderText(_translate("MainWindow", "Enter Password"))
        self.label_5.setText(_translate("MainWindow", "Role:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "-- Choose Role --"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Admin"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Manager"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Staff"))
        self.cancelBtn.setText(_translate("MainWindow", "Clear"))
        self.submitBtn.setText(_translate("MainWindow", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
