# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_suppliers_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 650)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget {\n"
"background-color:white;\n"
"}\n"
"#mainBody {\n"
"background-color:white;\n"
"border:1px solid rgb(222, 222, 222);\n"
"border-radius:2px;\n"
"}\n"
"QLineEdit {\n"
"padding:3px;\n"
"border:1px solid grey;\n"
"border-radius:2px;\n"
"}\n"
"QLineEdit:hover {\n"
"border-color:black;\n"
"}\n"
"#cancelBtn {\n"
"background-color:rgb(255, 78, 43);\n"
"color:white;\n"
"border:none;\n"
"padding:8px;\n"
"border-radius:3px;\n"
"}\n"
"#cancelBtn:hover {\n"
"background-color: rgb(202, 33, 0);\n"
"}\n"
"#submitBtn {\n"
"background-color:rgb(0, 149, 109);\n"
"color:white;\n"
"border:none;\n"
"padding:8px;\n"
"border-radius:3px;\n"
"}\n"
"#submitBtn:hover {\n"
"background-color:rgb(0, 121, 89);\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem = QtWidgets.QSpacerItem(302, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.mainBody = QtWidgets.QFrame(self.centralwidget)
        self.mainBody.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainBody.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainBody.setObjectName("mainBody")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.mainBody)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.frame_2 = QtWidgets.QFrame(self.mainBody)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.verticalLayout_7.addWidget(self.frame_2)
        self.name_Frame_2 = QtWidgets.QFrame(self.mainBody)
        self.name_Frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.name_Frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.name_Frame_2.setObjectName("name_Frame_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.name_Frame_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.name_Frame_2)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)
        self.name = QtWidgets.QLineEdit(self.name_Frame_2)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.verticalLayout_8.addWidget(self.name)
        self.verticalLayout_7.addWidget(self.name_Frame_2)
        self.address_Frame_2 = QtWidgets.QFrame(self.mainBody)
        self.address_Frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.address_Frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.address_Frame_2.setObjectName("address_Frame_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.address_Frame_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.address_Frame_2)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_9.addWidget(self.label_8)
        self.address = QtWidgets.QLineEdit(self.address_Frame_2)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.address.setFont(font)
        self.address.setObjectName("address")
        self.verticalLayout_9.addWidget(self.address)
        self.verticalLayout_7.addWidget(self.address_Frame_2)
        self.email_Frame_2 = QtWidgets.QFrame(self.mainBody)
        self.email_Frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.email_Frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.email_Frame_2.setObjectName("email_Frame_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.email_Frame_2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.email_Frame_2)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_10.addWidget(self.label_9)
        self.email = QtWidgets.QLineEdit(self.email_Frame_2)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.email.setFont(font)
        self.email.setObjectName("email")
        self.verticalLayout_10.addWidget(self.email)
        self.verticalLayout_7.addWidget(self.email_Frame_2)
        self.phone_no_Frame_2 = QtWidgets.QFrame(self.mainBody)
        self.phone_no_Frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.phone_no_Frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.phone_no_Frame_2.setObjectName("phone_no_Frame_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.phone_no_Frame_2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_10 = QtWidgets.QLabel(self.phone_no_Frame_2)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_11.addWidget(self.label_10)
        self.phone_no = QtWidgets.QLineEdit(self.phone_no_Frame_2)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.phone_no.setFont(font)
        self.phone_no.setObjectName("phone_no")
        self.verticalLayout_11.addWidget(self.phone_no)
        self.verticalLayout_7.addWidget(self.phone_no_Frame_2)
        self.buttons_Frame_2 = QtWidgets.QFrame(self.mainBody)
        self.buttons_Frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttons_Frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttons_Frame_2.setObjectName("buttons_Frame_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.buttons_Frame_2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(50)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.cancelBtn_frame_2 = QtWidgets.QFrame(self.buttons_Frame_2)
        self.cancelBtn_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cancelBtn_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cancelBtn_frame_2.setObjectName("cancelBtn_frame_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.cancelBtn_frame_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.cancelBtn = QtWidgets.QPushButton(self.cancelBtn_frame_2)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.cancelBtn.setFont(font)
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout_7.addWidget(self.cancelBtn)
        self.horizontalLayout_6.addWidget(self.cancelBtn_frame_2)
        self.submitBtn_frame_2 = QtWidgets.QFrame(self.buttons_Frame_2)
        self.submitBtn_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.submitBtn_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.submitBtn_frame_2.setObjectName("submitBtn_frame_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.submitBtn_frame_2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.submitBtn = QtWidgets.QPushButton(self.submitBtn_frame_2)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.submitBtn.setFont(font)
        self.submitBtn.setObjectName("submitBtn")
        self.horizontalLayout_8.addWidget(self.submitBtn)
        self.horizontalLayout_6.addWidget(self.submitBtn_frame_2)
        self.verticalLayout_7.addWidget(self.buttons_Frame_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.horizontalLayout_9.addWidget(self.mainBody)
        spacerItem3 = QtWidgets.QSpacerItem(302, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Add Suppliers Form"))
        self.label_6.setText(_translate("MainWindow", "Add Suppliers"))
        self.label_7.setText(_translate("MainWindow", "Name:"))
        self.name.setPlaceholderText(_translate("MainWindow", "Enter Name"))
        self.label_8.setText(_translate("MainWindow", "Address:"))
        self.address.setPlaceholderText(_translate("MainWindow", "Enter Address"))
        self.label_9.setText(_translate("MainWindow", "Email:"))
        self.email.setPlaceholderText(_translate("MainWindow", "Enter Email ID"))
        self.label_10.setText(_translate("MainWindow", "Phone no:"))
        self.phone_no.setPlaceholderText(_translate("MainWindow", "Enter Phone no"))
        self.cancelBtn.setText(_translate("MainWindow", "Clear"))
        self.submitBtn.setText(_translate("MainWindow", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
