# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forgotpassword.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 650)
        MainWindow.setMaximumSize(QtCore.QSize(950, 650))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget {\n"
"background-color:white;\n"
"}\n"
"#mainBody {\n"
"background-color:white;\n"
"border:1px solid rgb(222, 222, 222);\n"
"border-radius:2px;\n"
"}\n"
"QLineEdit {\n"
"padding:3px;\n"
"border:1px solid grey;\n"
"border-radius:2px;\n"
"}\n"
"QLineEdit:hover {\n"
"border-color:black;\n"
"}\n"
"#cancelBtn {\n"
"background-color:#0b3d91;\n"
"color:white;\n"
"border:none;\n"
"padding:8px;\n"
"border-radius:3px;\n"
"}\n"
"#cancelBtn:hover {\n"
"background-color: rgb(202, 33, 0);\n"
"}\n"
"#submitBtn {\n"
"background-color:#0b3d91;\n"
"color:white;\n"
"border:none;\n"
"padding:8px;\n"
"border-radius:3px;\n"
"}\n"
"#submitBtn:hover {\n"
"background-color:#2956be;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.mainBody = QtWidgets.QFrame(self.centralwidget)
        self.mainBody.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainBody.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainBody.setObjectName("mainBody")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainBody)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.frame = QtWidgets.QFrame(self.mainBody)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.frame)
        self.name_Frame = QtWidgets.QFrame(self.mainBody)
        self.name_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.name_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.name_Frame.setObjectName("name_Frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.name_Frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.name_Frame)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.customer_name = QtWidgets.QLineEdit(self.name_Frame)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.customer_name.setFont(font)
        self.customer_name.setObjectName("customer_name")
        self.verticalLayout_3.addWidget(self.customer_name)
        self.verticalLayout_2.addWidget(self.name_Frame)
        self.address_Frame = QtWidgets.QFrame(self.mainBody)
        self.address_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.address_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.address_Frame.setObjectName("address_Frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.address_Frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.address_Frame)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.customer_address = QtWidgets.QLineEdit(self.address_Frame)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.customer_address.setFont(font)
        self.customer_address.setObjectName("customer_address")
        self.verticalLayout_4.addWidget(self.customer_address)
        self.verticalLayout_2.addWidget(self.address_Frame)
        self.buttons_Frame = QtWidgets.QFrame(self.mainBody)
        self.buttons_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttons_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttons_Frame.setObjectName("buttons_Frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.buttons_Frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.buttons_Frame)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(9)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.submitBtn = QtWidgets.QPushButton(self.buttons_Frame)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.submitBtn.setFont(font)
        self.submitBtn.setObjectName("submitBtn")
        self.verticalLayout.addWidget(self.submitBtn)
        self.verticalLayout_2.addWidget(self.buttons_Frame)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_5.addWidget(self.mainBody)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Add Customers Form"))
        self.label.setText(_translate("MainWindow", "Change Your Password?"))
        self.label_2.setText(_translate("MainWindow", "New Password:"))
        self.customer_name.setPlaceholderText(_translate("MainWindow", "New Password"))
        self.label_3.setText(_translate("MainWindow", "Confirm Password:"))
        self.customer_address.setPlaceholderText(_translate("MainWindow", "Confirm Your Password"))
        self.checkBox.setText(_translate("MainWindow", "Remember me"))
        self.submitBtn.setText(_translate("MainWindow", "Change Password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
